services:
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: authdb
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./db/auth/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20


  listing-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: listingdb
    volumes:
      - listing_db_data:/var/lib/postgresql/data
      - ./db/listing/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  trade-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: tradedb
    volumes:
      - trade_db_data:/var/lib/postgresql/data
      - ./db/trade/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20


  fx-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: fxdb
    volumes:
      - fx_db_data:/var/lib/postgresql/data
      - ./db/fx/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  shipping-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: shippinguser
      POSTGRES_PASSWORD: shippingpass
      POSTGRES_DB: shippingdb
    volumes:
      - shipping_db_data:/var/lib/postgresql/data
      - ./db/shipping/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20


  auth-svc:
    build: ./services/auth-svc
    environment:
      DB_HOST: auth-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: authdb
      JWT_SECRET: mysecret
      NODE_ENV: production
      INTERNAL_TOKEN: internal-secret
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "4100:4000"

  listing-svc:
    build: ./services/listing-svc
    environment:
      DB_HOST: listing-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: listingdb
      JWT_SECRET: mysecret
      NODE_ENV: production
      INTERNAL_TOKEN: internal-secret
    depends_on:
      listing-db:
        condition: service_healthy
    ports:
      - "4110:4010"
    volumes:
      - ./data/listing-uploads:/app/uploads

  trade-svc:
    build: ./services/trade-svc
    environment:
      DB_HOST: trade-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: tradedb
      JWT_SECRET: mysecret
      NODE_ENV: production
      INTERNAL_TOKEN: internal-secret
      LISTING_SVC_URL: http://listing-svc:4010
      FX_SVC_URL: http://fx-svc:4030
      SHIPPING_SVC_URL: http://shipping-svc:4040
    depends_on:
      trade-db:
        condition: service_healthy
      listing-svc:
        condition: service_started
      auth-svc:
        condition: service_started
    ports:
      - "4120:4020"

  shipping-svc:
    build: ./services/shipping-svc
    environment:
      DB_HOST: shipping-db
      DB_USER: shippinguser
      DB_PASSWORD: shippingpass
      DB_NAME: shippingdb
      PORT: 4040
      INTERNAL_TOKEN: internal-secret
      AUTH_SVC_URL: http://auth-svc:4000
    depends_on:
      shipping-db:
        condition: service_healthy
      auth-svc:
        condition: service_started
    ports:
      - "4140:4040"


  frontend:
    build: ./frontend
    environment:
      VITE_AUTH_URL: "http://localhost:4100"
      VITE_LISTING_URL: "http://localhost:4110"
      VITE_TRADE_URL: "http://localhost:4120"
      VITE_FX_URL: "http://localhost:4130"
    depends_on:
      auth-svc:
        condition: service_started
      listing-svc:
        condition: service_started
      trade-svc:
        condition: service_started
    ports:
      - "3100:3000"



  fx-svc:
    build: ./services/fx-svc
    environment:
      DB_HOST: fx-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: fxdb
      INTERNAL_TOKEN: internal-secret
      NODE_ENV: production
      CORS_ORIGIN: "http://localhost:3100"
      PORT: 4030
    depends_on:
      fx-db:
        condition: service_healthy
    ports:
      - "4130:4030"



volumes:
  auth_db_data:
  listing_db_data:
  trade_db_data:
  fx_db_data:
  shipping_db_data:

