services:
  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: authdb
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./db/auth/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  listing-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: listingdb
    volumes:
      - listing_db_data:/var/lib/postgresql/data
      - ./db/listing/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d listingdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  trade-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: tradedb
    volumes:
      - trade_db_data:/var/lib/postgresql/data
      - ./db/trade/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d tradedb"]
      interval: 5s
      timeout: 3s
      retries: 20



  auth-svc:
    build: ./services/auth-svc
    environment:
      DB_HOST: auth-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: authdb
      JWT_SECRET: mysecret
      NODE_ENV: production
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "4100:4000"

  listing-svc:
    build: ./services/listing-svc
    environment:
      DB_HOST: listing-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: listingdb
      JWT_SECRET: mysecret
      NODE_ENV: production
      INTERNAL_TOKEN: internal-secret
    depends_on:
      listing-db:
        condition: service_healthy
    ports:
      - "4110:4010"
    volumes:
      - ./data/listing-uploads:/app/uploads

  trade-svc:
    build: ./services/trade-svc
    environment:
      DB_HOST: trade-db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: tradedb
      JWT_SECRET: mysecret
      NODE_ENV: production
      INTERNAL_TOKEN: internal-secret
      LISTING_SVC_URL: http://listing-svc:4010
    depends_on:
      trade-db:
        condition: service_healthy
      listing-svc:
        condition: service_started
      auth-svc:
        condition: service_started
    ports:
      - "4120:4020"



  frontend:
    build: ./frontend
    environment:
      VITE_AUTH_URL: "http://localhost:4100"
      VITE_LISTING_URL: "http://localhost:4110"
      VITE_TRADE_URL: "http://localhost:4120"
    depends_on:
      auth-svc:
        condition: service_started
      listing-svc:
        condition: service_started
      trade-svc:
        condition: service_started
    ports:
      - "3100:3000"


volumes:
  auth_db_data:
  listing_db_data:
  trade_db_data:
